#!/bin/bash
for opt in "$@"
do
    case "$1" in
        --) shift ; break ;;
        -*) shift ;;
        *) break ;;
    esac
done

export FAKEROOTDONTTRYCHOWN=true
if [[ -n "${@}" ]]
then
  if [[ $FAKECHROOT == true ]]
  then
      fakechrootcmd=""
  else
      fakechrootcmd="fakechroot --lib $HOME/.junest/lib/libfakeroot/fakechroot/libfakechroot.so"
  fi

  if [[ -n $FAKED_MODE ]]
  then
      fakerootcmd=""
  else
      fakerootcmd="/usr/bin/fakeroot --lib $HOME/.junest/lib/libfakeroot/libfakeroot.so"
  fi

  $fakechrootcmd $fakerootcmd "${@}"
fi